language: node_js
node_js:
  - "10.0"
before_install:
  - npm install -g typescript

dist: trusty
sudo: false

jobs:
  include:
    - stage: "Tests"
      script: npm test
      name: "Unit Tests"
    - script: npm run type-check
      name: "Type Check"
